function out = run_pyfai_multigeometry_from_matlab(imgPaths, poniPaths, wavelength_m, cfg)
% Runs pyFAI MultiGeometry via external python process, returns result in MATLAB.

if nargin < 4 || isempty(cfg), cfg = struct(); end
if ~iscell(imgPaths), imgPaths = cellstr(imgPaths); end
if ~iscell(poniPaths), poniPaths = cellstr(poniPaths); end
if numel(imgPaths) ~= numel(poniPaths)
    error("imgPaths and poniPaths must have same length");
end

% defaults
cfg = setDefault(cfg,"pythonExe","python");
cfg = setDefault(cfg,"scriptPath", fullfile(tempdir,"pyfai_multigeom_run.py"));
cfg = setDefault(cfg,"outBase", fullfile(pwd,"pyfai_multigeom_out"));
cfg = setDefault(cfg,"mode","2d");                 % "2d" or "1d"
cfg = setDefault(cfg,"unit","2th_deg");            % "2th_deg" or "q_A^-1"
cfg = setDefault(cfg,"npt_rad", 2000);
cfg = setDefault(cfg,"npt_azim", 360);
cfg = setDefault(cfg,"method","csr");
cfg = setDefault(cfg,"correctSolidAngle", true);
cfg = setDefault(cfg,"polarization_factor", NaN);
cfg = setDefault(cfg,"dummy", NaN);
cfg = setDefault(cfg,"delta_dummy", NaN);
cfg = setDefault(cfg,"dark", "");
cfg = setDefault(cfg,"flat", "");
cfg = setDefault(cfg,"mask", "");
cfg = setDefault(cfg,"chi_discont_deg", 180);
cfg = setDefault(cfg,"error_model", "poisson");
cfg = setDefault(cfg,"verbose", true);

cfg.outBase  = char(string(cfg.outBase));
cfg.pythonExe = char(string(cfg.pythonExe));
cfg.scriptPath = char(string(cfg.scriptPath));

cfg.outBase = char(string(cfg.outBase));

ensure_py_script(cfg.scriptPath);

job = struct();
job.img_paths = imgPaths;
job.poni_paths = poniPaths;
job.wavelength_m = wavelength_m;
job.mode = cfg.mode;
job.unit = cfg.unit;
job.npt_rad = cfg.npt_rad;
job.npt_azim = cfg.npt_azim;
job.method = cfg.method;
job.correctSolidAngle = cfg.correctSolidAngle;
job.polarization_factor = cfg.polarization_factor;
job.dummy = cfg.dummy;
job.delta_dummy = cfg.delta_dummy;
job.dark = cfg.dark;
job.flat = cfg.flat;
job.mask = cfg.mask;
job.chi_discont_deg = cfg.chi_discont_deg;
job.error_model = cfg.error_model;

job.out_mat  = char(string(cfg.outBase) + ".mat");
job.out_npz  = char(string(cfg.outBase) + ".npz");
job.out_json = char(string(cfg.outBase) + ".json");

jobJsonPath = char(string(cfg.outBase) + "_job.json");
write_json(jobJsonPath, job);

cmd = sprintf('"%s" "%s" "%s"', cfg.pythonExe, cfg.scriptPath, jobJsonPath);
if cfg.verbose
    fprintf("Running: %s\n", cmd);
end
[status, msg] = system(cmd);
if status ~= 0
    error("pyFAI MultiGeometry failed.\nCommand:\n%s\n\nOutput:\n%s", cmd, msg);
end
if cfg.verbose
    fprintf("%s\n", msg);
end

outMatPath = char(string(job.out_mat));
if ~exist(outMatPath,"file")
    error("Python did not create MAT file: %s\nCheck Python console output above.", outMatPath);
end
% S = load(outMatPath);

S = load(char(string(job.out_mat)));
out = S;                       % enthält I, radial, (azimuthal)
out.meta = read_json(job.out_json);
% Am Ende von run_pyfai_multigeometry_from_matlab:
out.matPath      = job.out_mat;    % Pfad zur gecakten .mat
out.rawStackPath = strrep(job.out_mat, '.mat', '_raw_stack.mat');
out.ringPath     = strrep(job.out_mat, '.mat', '_ring.mat');

% Geometrie-Parameter aus erster PONI-Datei lesen
% (für Ring-Darstellung in MATLAB)
try
    poni1   = poniPaths{1};
    fid     = fopen(poni1, 'r');
    txt     = fread(fid, '*char')';
    fclose(fid);

    % Distance (m -> mm)
    tok = regexp(txt, 'Distance:\s*([\d.eE+-]+)', 'tokens');
    if ~isempty(tok), out.sdd_mm = str2double(tok{1}{1}) * 1000; end

    % Poni1, Poni2 (m -> mm) = Strahlmitte auf Detektor
    tok = regexp(txt, 'Poni1:\s*([\d.eE+-]+)', 'tokens');
    if ~isempty(tok), out.center_y_mm = str2double(tok{1}{1}) * 1000; end
    tok = regexp(txt, 'Poni2:\s*([\d.eE+-]+)', 'tokens');
    if ~isempty(tok), out.center_x_mm = str2double(tok{1}{1}) * 1000; end
catch
    out.sdd_mm      = [];
    out.center_x_mm = [];
    out.center_y_mm = [];
end

end

%% helpers
function cfg = setDefault(cfg, field, val)
if ~isfield(cfg,field) || isempty(cfg.(field))
    cfg.(field) = val;
end
end

function ensure_py_script(scriptPath)
if exist(scriptPath,"file"), return; end
fid = fopen(scriptPath,"w");
assert(fid>0, "Cannot write python script to %s", scriptPath);
fwrite(fid, py_script_contents());
fclose(fid);
end

function txt = py_script_contents()
txt = [
"import json, sys" newline ...
"import numpy as np" newline ...
"" newline ...
"def main(job_json):" newline ...
"    with open(job_json, 'r') as f:" newline ...
"        job = json.load(f)" newline ...
"" newline ...
"    # --- version / environment debug ---" newline ...
"    try:" newline ...
"        import importlib.metadata as m" newline ...
"        print('pyFAI dist version:', m.version('pyFAI'))" newline ...
"    except Exception as e:" newline ...
"        print('pyFAI version lookup failed:', e)" newline ...
"    try:" newline ...
"        import scipy" newline ...
"        print('scipy version:', scipy.__version__)" newline ...
"    except Exception as e:" newline ...
"        print('scipy import failed:', e)" newline ...
"" newline ...
"    import pyFAI" newline ...
"    from pyFAI.multi_geometry import MultiGeometry" newline ...
"    import fabio" newline ...
"    from scipy.io import savemat" newline ...
"" newline ...
"    img_paths = job['img_paths']" newline ...
"    poni_paths = job['poni_paths']" newline ...
"    wavelength_m = float(job['wavelength_m'])" newline ...
"" newline ...
"    # --- load geometries (one AzimuthalIntegrator per PONI) ---" newline ...
"    ais = []" newline ...
"    for p in poni_paths:" newline ...
"        ai = pyFAI.load(p)" newline ...
"        ai.wavelength = wavelength_m" newline ...
"        ais.append(ai)" newline ...
"" newline ...
"    chi_disc = job.get('chi_discont_deg', 180)" newline ...
"    mg = MultiGeometry(ais, chi_disc=chi_disc)" newline ...
"" newline ...
"    # --- optional keyword args ---" newline ...
"    kwargs = {}" newline ...
"    if job.get('correctSolidAngle', True):" newline ...
"        kwargs['correctSolidAngle'] = True" newline ...
"" newline ...
"    pf = job.get('polarization_factor', None)" newline ...
"    if isinstance(pf, (int, float)) and not np.isnan(pf):" newline ...
"        kwargs['polarization_factor'] = float(pf)" newline ...
"" newline ...
"    dummy = job.get('dummy', None)" newline ...
"    if isinstance(dummy, (int, float)) and not np.isnan(dummy):" newline ...
"        kwargs['dummy'] = float(dummy)" newline ...
"" newline ...
"    dd = job.get('delta_dummy', None)" newline ...
"    if isinstance(dd, (int, float)) and not np.isnan(dd):" newline ...
"        kwargs['delta_dummy'] = float(dd)" newline ...
"" newline ...
"    for k in ['dark', 'flat', 'mask']:" newline ...
"        v = job.get(k, '')" newline ...
"        if isinstance(v, str) and len(v) > 0:" newline ...
"            kwargs[k] = v" newline ...
"" newline ...
"    method = job.get('method', 'csr')" newline ...
"    error_model = job.get('error_model', 'poisson')" newline ...
"" newline ...
"    mode = job.get('mode', '2d')" newline ...
"    unit = job.get('unit', '2th_deg')" newline ...
"    npt_rad = int(job.get('npt_rad', 2000))" newline ...
"    npt_azim = int(job.get('npt_azim', 360))" newline ...
"" newline ...
"    out_npz = job.get('out_npz', 'out.npz')" newline ...
"    out_mat = job.get('out_mat', 'out.mat')" newline ...
"" newline ...
"    # --- read images into numpy arrays ---" newline ...
"    imgs = []" newline ...
"    for ip in img_paths:" newline ...
"        imgs.append(fabio.open(ip).data.astype(np.float32))" newline ...
"" newline ...
"    if mode == '2d':" newline ...
"        res = mg.integrate2d(imgs, npt_rad, npt_azim, unit=unit, method=method, error_model=error_model, **kwargs)" newline ...
"        if isinstance(res, tuple) and len(res) >= 3:" newline ...
"            I, radial, azim = res[0], res[1], res[2]" newline ...
"        else:" newline ...
"            I, radial, azim = res.intensity, res.radial, res.azimuthal" newline ...
"" newline ...
"        I = np.asarray(I)" newline ...
"        radial = np.asarray(radial)" newline ...
"        azim = np.asarray(azim)" newline ...
"        # enforce I shape = [nRad, nAzim]" newline ...
"        if I.shape == (azim.size, radial.size):" newline ...
"        I = I.T" newline ...
"" newline ...
"        np.savez(out_npz, I=I, radial=radial, azimuthal=azim)" newline ...
"        savemat(out_mat, {'I': I, 'radial': radial, 'azimuthal': azim})" newline ...
"" newline ...
"        print('OK: wrote', out_npz, 'and', out_mat)" newline ...
"" newline ...
"    elif mode == '1d':" newline ...
"        res = mg.integrate1d(imgs, npt_rad, unit=unit, method=method, error_model=error_model, **kwargs)" newline ...
"        if isinstance(res, tuple) and len(res) >= 2:" newline ...
"            radial, I = res[0], res[1]" newline ...
"        else:" newline ...
"            radial, I = res.radial, res.intensity" newline ...
"" newline ...
"        I = np.asarray(I)" newline ...
"        radial = np.asarray(radial)" newline ...
"" newline ...
"        np.savez(out_npz, I=I, radial=radial)" newline ...
"        savemat(out_mat, {'I': I, 'radial': radial})" newline ...
"" newline ...
"        print('OK: wrote', out_npz, 'and', out_mat)" newline ...
"    else:" newline ...
"        raise ValueError('mode must be ''1d'' or ''2d''')" newline ...
"" newline ...
"if __name__ == '__main__':" newline ...
"    if len(sys.argv) < 2:" newline ...
"        print('usage: pyfai_multigeom_run.py job.json')" newline ...
"        sys.exit(2)" newline ...
"    main(sys.argv[1])" newline ...
];
end

function write_json(path, s)
    path = char(string(path));

    % Ordner anlegen falls nicht vorhanden
    folder = fileparts(path);
    if ~isempty(folder) && ~exist(folder, 'dir')
        [ok, msg] = mkdir(folder);
        if ~ok
            error('write_json: Ordner konnte nicht angelegt werden:\n%s\nFehler: %s', folder, msg);
        end
    end

    % JSON schreiben
    fid = fopen(path, 'w');
    if fid == -1
        error('write_json: Datei konnte nicht geöffnet werden:\n%s', path);
    end

    try
        txt = jsonencode(s);
        fwrite(fid, txt, 'char');
        fclose(fid);
    catch ME
        fclose(fid);
        rethrow(ME);
    end

    % Sofort prüfen ob Datei wirklich existiert
    if ~exist(path, 'file')
        error('write_json: Datei wurde nicht erstellt:\n%s', path);
    end
end

function s = read_json(path)
s = jsondecode(fileread(path));
end
