function h = updateStressPlots(h, valueSlider)

eps = h.epsfitdataexport{valueSlider};
erg = h.epsgammaergfunc{valueSlider};

% --- ε(γ)-Plot ---
idxFin = isfinite(eps(:,2));
if any(idxFin)
    set(h.plotdata, ...
        'XData',          eps(idxFin,1), ...
        'YData',          eps(idxFin,2), ...
        'YNegativeDelta', abs(eps(idxFin,3)), ...
        'YPositiveDelta', abs(eps(idxFin,3)), ...
        'Visible', 'on');
else
    set(h.plotdata, 'XData', NaN, 'YData', NaN, ...
        'YNegativeDelta', NaN, 'YPositiveDelta', NaN, 'Visible', 'off');
end


% Fit-Kurve: XData muss gleiche Länge wie YData haben
% ergVec = erg(:);   % immer Spaltenvektor
% if numel(ergVec) == size(eps,1)
%     % Fit-Kurve auf denselben X-Werten wie Datenpunkte
%     set(h.fitcurvestress, ...
%         'XData',   eps(:,1), ...
%         'YData',   ergVec, ...
%         'Visible', 'on');
% else
%     % Längen passen nicht → Fit-Kurve ausblenden
%     set(h.fitcurvestress, 'Visible', 'off');
% end

if isfield(h,'epsgammaergfunc_x') && numel(h.epsgammaergfunc_x) >= valueSlider && ...
   ~isempty(h.epsgammaergfunc_x{valueSlider})
    set(h.fitcurvestress, ...
        'XData',   h.epsgammaergfunc_x{valueSlider}(:), ...
        'YData',   h.epsgammaergfunc{valueSlider}(:), ...
        'Visible', 'on');
else
    % Fallback: diskrete Punkte
    ergVec = h.epsgammaergfunc{valueSlider}(:);
    eps    = h.epsfitdataexport{valueSlider};
    if numel(ergVec) == size(eps,1)
        set(h.fitcurvestress, ...
            'XData',   eps(:,1), ...
            'YData',   ergVec, ...
            'Visible', 'on');
    else
        set(h.fitcurvestress, 'Visible', 'off');
    end
end

% --- sin²ψ-Plot ---
s2p = h.epssin2psifitdaten{valueSlider};
idxFin2 = isfinite(s2p(:,2));
if any(idxFin2)
    set(h.plotdatasin2psi, ...
        'XData',          s2p(idxFin2,1), ...
        'YData',          s2p(idxFin2,2), ...
        'YNegativeDelta', abs(s2p(idxFin2,3)), ...
        'YPositiveDelta', abs(s2p(idxFin2,3)), ...
        'Visible', 'on');
else
    set(h.plotdatasin2psi, 'XData', NaN, 'YData', NaN, ...
        'YNegativeDelta', NaN, 'YPositiveDelta', NaN, 'Visible', 'off');
end

reg = h.sin2psiregres{valueSlider};
if numel(reg) == 21   % erwartet 0:0.05:1 = 21 Punkte
    set(h.fitcurvestresssin2psi, ...
        'XData',   0:0.05:1, ...
        'YData',   reg, ...
        'Visible', 'on');
else
    set(h.fitcurvestresssin2psi, 'Visible', 'off');
end

% --- Spannungsplot ---
% Sicherstellen dass taumean und sigmaFinal gleiche Länge haben
nPeaks = numel(h.taumean);
if size(h.sigmaFinal,1) == nPeaks && size(h.sigmaerrFinal,1) == nPeaks
    set(h.plotstressdata, ...
        'XData',          h.taumean(:), ...
        'YData',          h.sigmaFinal(:,1), ...
        'YNegativeDelta', abs(h.sigmaerrFinal(:,1)), ...
        'YPositiveDelta', abs(h.sigmaerrFinal(:,1)), ...
        'Visible', 'on');
    set(h.plotsin2psistressdata, ...
        'XData',          h.taumean(:), ...
        'YData',          h.sigmasin2psiFinal(:), ...
        'YNegativeDelta', abs(h.deltasigmasin2psiFinal(:)), ...
        'YPositiveDelta', abs(h.deltasigmasin2psiFinal(:)), ...
        'Visible', 'on');
else
    set(h.plotstressdata,      'Visible', 'off');
    set(h.plotsin2psistressdata,'Visible', 'off');
end

% --- XLim des Stress-Plots dynamisch anpassen ────────────────────────
if isfield(h,'taumean') && ~isempty(h.taumean)
    tauFinite = h.taumean(isfinite(h.taumean));
    if ~isempty(tauFinite)
        tauMax    = max(tauFinite);
        tauMargin = max(0.5, tauMax * 0.10);
        h.axesStressData.XLim = [0, tauMax + tauMargin];
    end
end


% --- Highlight im Spannungsplot ---
if isfield(h,'highlightstressplot') && isvalid(h.highlightstressplot) && ...
   valueSlider <= nPeaks
    set(h.highlightstressplot, ...
        'XData',   h.taumean(valueSlider), ...
        'YData',   h.sigmaFinal(valueSlider,1), ...
        'Visible', 'on');
end

% --- Tau-Plot ---
if isfield(h,'tau') && numel(h.tau) >= valueSlider && ...
   ~isempty(h.tau{valueSlider})
    tauVec = h.tau{valueSlider}(:);
    xVec   = h.FitDataMod{valueSlider}(:,1);
    if numel(tauVec) == numel(xVec)
        set(h.plottaudata, 'XData', xVec, 'YData', tauVec);
        set(h.plottaudatamean, 'XData', xVec, ...
            'YData', repelem(mean(tauVec), numel(xVec)));
        h.axesPlottauData.XLim = h.axes.XLim;
    end
end

% --- Achsenlabel (KEIN YLim setzen — wird vom Aufrufer gesetzt) ---
h.axes.YLabel.String = [char(949), '(', char(947), ')'];

end


% function h = updateStressPlots(h, valueSlider)
% % UPDATESTRESSPLOTS  Aktualisiert alle Stress- und Tau-Plots.
% %
% %   h            - guidata Struktur
% %   valueSlider  - Index des aktuell ausgewählten Peaks
% 
% % --- ε(γ)-Plot ---
% set(h.plotdata, ...
%     'XData',          h.epsfitdataexport{valueSlider}(:,1), ...
%     'YData',          h.epsfitdataexport{valueSlider}(:,2), ...
%     'YNegativeDelta', h.epsfitdataexport{valueSlider}(:,3), ...
%     'YPositiveDelta', h.epsfitdataexport{valueSlider}(:,3), ...
%     'Visible', 'on');
% 
% set(h.fitcurvestress, ...
%     'XData',   h.epsfitdataexport{valueSlider}(:,1), ...
%     'YData',   h.epsgammaergfunc{valueSlider}', ...
%     'Visible', 'on');
% 
% % --- sin²ψ-Plot ---
% set(h.plotdatasin2psi, ...
%     'XData',          h.epssin2psifitdaten{valueSlider}(:,1), ...
%     'YData',          h.epssin2psifitdaten{valueSlider}(:,2), ...
%     'YNegativeDelta', h.epssin2psifitdaten{valueSlider}(:,3), ...
%     'YPositiveDelta', h.epssin2psifitdaten{valueSlider}(:,3), ...
%     'Visible', 'on');
% 
% set(h.fitcurvestresssin2psi, ...
%     'XData',   0:0.05:1, ...
%     'YData',   h.sin2psiregres{valueSlider}, ...
%     'Visible', 'on');
% 
% % --- Spannungsplot ---
% set(h.plotstressdata, ...
%     'XData',          h.taumean, ...
%     'YData',          h.sigmaFinal(:,1), ...
%     'YNegativeDelta', h.sigmaerrFinal(:,1), ...
%     'YPositiveDelta', h.sigmaerrFinal(:,1), ...
%     'Visible', 'on');
% 
% set(h.plotsin2psistressdata, ...
%     'XData',          h.taumean, ...
%     'YData',          h.sigmasin2psiFinal, ...
%     'YNegativeDelta', h.deltasigmasin2psiFinal, ...
%     'YPositiveDelta', h.deltasigmasin2psiFinal, ...
%     'Visible', 'on');
% 
% % --- Highlight im Spannungsplot ---
% if isfield(h, 'taumean') && isfield(h, 'highlightstressplot') && isvalid(h.highlightstressplot)
%     set(h.highlightstressplot, ...
%         'XData',   h.taumean(valueSlider), ...
%         'YData',   h.sigmaFinal(valueSlider,1), ...
%         'Visible', 'on');
% end
% 
% % --- Tau-Plot ---
% if isfield(h, 'tau') && numel(h.tau) >= valueSlider && ~isempty(h.tau{valueSlider})
%     set(h.plottaudata, ...
%         'XData', h.FitDataMod{valueSlider}(:,1), ...
%         'YData', h.tau{valueSlider});
%     set(h.plottaudatamean, ...
%         'XData', h.FitDataMod{valueSlider}(:,1), ...
%         'YData', repelem(mean(h.tau{valueSlider}), size(h.FitDataMod{valueSlider},1)));
%     h.axesPlottauData.XLim = h.axes.XLim;
% end
% 
% % --- Achsenlabels ---
% h.axes.YLabel.String = [char(949), '(', char(947), ')'];
% h.axes.YLim          = [-Inf, Inf];
% 
% end